//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fingerprint
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PlagarismDbEntities : DbContext
    {
        public PlagarismDbEntities()
            : base("name=PlagarismDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Calculation> Calculations { get; set; }
        public DbSet<Document> Documents { get; set; }
        public DbSet<Result> Results { get; set; }
        public DbSet<SimilarWord> SimilarWords { get; set; }
    }
}
