//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fingerprint
{
    using System;
    using System.Collections.Generic;
    
    public partial class SimilarWord
    {
        public System.Guid pairid { get; set; }
        public System.Guid docid { get; set; }
        public int dictionaryid { get; set; }
        public string word { get; set; }
    
        public virtual Document Document { get; set; }
    }
}
